/* ============================================================
   多彩手账 · v003
   P0-1: main.insertBefore 第一位 + 隐藏旧.hero
   P0-2: D2 无贴纸双层标题
   P0-3: 真实高德地图 180px
   P0-4: touch-action 已修正
   P1: 手机顶栏/微信标签/动态内容API/mascot eager
   ============================================================ */
(function(){'use strict';
function isActive(){return window.innerWidth<=860}
var I={home:'<svg viewBox="0 0 24 24"><path d="m3 11 9-8 9 8v9H3zM9 20v-6h6v6"/></svg>',guide:'<svg viewBox="0 0 24 24"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20V4H6.5A2.5 2.5 0 0 0 4 6.5zM4 6.5v13"/></svg>',ask:'<svg viewBox="0 0 24 24"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"/></svg>',map:'<svg viewBox="0 0 24 24"><path d="M3 6l6-3 6 3 6-3v15l-6 3-6-3-6 3zM9 3v15M15 6v15"/></svg>',service:'<svg viewBox="0 0 24 24"><path d="M6 8h12l1 12H5zM9 8V6a3 3 0 0 1 6 0v2"/></svg>',arrowDown:'<svg viewBox="0 0 24 24"><path d="M12 5v14M6 13l6 6 6-6"/></svg>',x:'<svg viewBox="0 0 24 24"><path d="M18 6 6 18M6 6l12 12"/></svg>',copy:'<svg viewBox="0 0 24 24"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>',check:'<svg viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5"/></svg>',package2:'<svg viewBox="0 0 24 24"><path d="M4 7h16v11H4zM8 7V4h8v3M4 12h16"/></svg>',wifi:'<svg viewBox="0 0 24 24"><path d="M5 12.5a10 10 0 0 1 14 0M8 16a6 6 0 0 1 8 0M11 19.5a2 2 0 0 1 2 0"/></svg>',building:'<svg viewBox="0 0 24 24"><path d="M4 19V8h16v11M7 8V5h4v3M14 8V5h3v3M8 13h8"/></svg>',creditCard:'<svg viewBox="0 0 24 24"><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 7h6M9 11h6M9 15h3"/></svg>',bike:'<svg viewBox="0 0 24 24"><circle cx="7" cy="17" r="3"/><circle cx="17" cy="17" r="3"/><path d="M7 17l4-8h4l2 8M10 12h8"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',more:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/></svg>',lockKeyhole:'<svg viewBox="0 0 24 24"><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/><circle cx="12" cy="16" r="1"/></svg>',waves:'<svg viewBox="0 0 24 24"><path d="M2 12h2M6 8h2M6 16h2M10 6h2M10 14h2M10 18h2M14 8h2M14 16h2M18 6h2M18 12h2M18 18h2M22 12h2"/></svg>'};
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function $(s,r){return(r||document).querySelector(s)}
function $$(s,r){return Array.from((r||document).querySelectorAll(s))}

var W={nickname:'onlyuandme',id:'ydhjdsyn',copy:'有不明白的直接问。如果刚好需要校园卡或出行建议，也可以找学长聊聊。',qr:'assets/images/wechat-qr-onlyuandme.jpg'};

var QQ=[
  {key:'express',icon:I.package2,title:'快递在哪里取？',answer:'学校快递点集中在<strong>同大、西区、博雅苑、东区</strong>四个区域。每个快递公司对应的站点不同，建议先确认取件码上的站点名称。<br><br>如果找不到，可以直接问学长，我帮你判断在哪个站点。',linkTo:'express',linkText:'看全部快递攻略'},
  {key:'network',icon:I.wifi,title:'校园网怎么办？',answer:'校园网需要先办理校园卡，再登录网站完成认证后才能联网。网速肯定没有家里快，但在宿舍用电脑上网<strong>基本不会卡顿</strong>。<br><br>学长这一年加上舍友的实际体验，明显卡顿的次数加起来不超过十次。',linkTo:'',linkText:''},
  {key:'dorm',icon:I.building,title:'宿舍条件怎么样？',answer:'宿舍分不同片区和楼栋，条件有差异。大部分是<strong>六人间或八人间</strong>，有独立卫生间和空调。<br><br>具体被分到哪栋楼，报到时会在对应专业的报到处知晓。',linkTo:'dorms',linkText:'看寝室板块详情'},
  {key:'campusCard',icon:I.creditCard,title:'校园卡怎么办？',answer:'校园卡（电话卡）不是必须办的。报到时运营商会设帐篷推广，<strong>建议先了解套餐内容再决定</strong>。<br><br><strong>2025 年参考套餐</strong>（实际以当年现场政策为准）：<br><br><strong>移动：</strong>120G 全国通用流量、130G 部分 App 专属流量、300G 校园内专属流量；每月可选一款平台会员、代金券或礼包；5M 校园网带宽；月付 39 元。<br><br><strong>联通：</strong>350G 全国通用流量、300G 校园专属流量；每月可选一款平台会员、代金券或礼包；10M 校园网带宽；月付 39 元。<strong>以上流量为计入结转后的参考总量。</strong>流量通常用不完，未用完的流量会按套餐规则继续结转，因此实际可用流量会很多。<br><br><strong>电信：</strong>240G 全国通用流量、100G 湖北省流量、400G 校园流量、170G 定向流量；每月可选一款平台会员、代金券或礼包；5M 校园网带宽；月付 39 元。<br><br>如果你已经有合适的卡，完全不需要额外办一张。',linkTo:'',linkText:''},
  {key:'ebike',icon:I.bike,title:'电动车有必要买吗？',answer:'看你的<strong>宿舍到教学楼的距离</strong>。如果分在同大或本院内较远的楼栋，电动车会方便很多。<br><br>校内也有小公交和共享单车，建议先体验一周再决定。',linkTo:'traffic',linkText:'看交通板块详情'}
];

var S={activeTab:'home',wechatOpen:false,quickOpen:null,journalMap:null};
function destroyJournalMap(){if(S.journalMap&&typeof S.journalMap.destroy==='function'){try{S.journalMap.destroy()}catch(e){}}S.journalMap=null}

/* ===== P1: 动态内容API — 读取script.js暴露的实时数据 ===== */
function getSections(){if(typeof window.__journalGetSections==='function')return window.__journalGetSections();var d=window.HBEU_SITE_DATA;return d&&d.sections?d.sections:[]}
function getQas(){if(typeof window.__journalGetQas==='function')return window.__journalGetQas();var d=window.HBEU_SITE_DATA;return d&&d.qas?d.qas:[]}
function getRoutes(){if(typeof window.__journalGetRoutes==='function')return window.__journalGetRoutes();var d=window.HBEU_SITE_DATA;return d&&d.routes?d.routes:[]}

/* ===== P1: 手机顶栏 ===== */
function buildMobileTopbar(){return '<header class="mobile-topbar"><div class="j-identity"><div class="j-avatar">鹿</div><span>长颈鹿学长</span></div><div class="j-top-actions"><button class="j-icon-btn" data-j-admin="" aria-label="搜索">'+I.search+'</button><button class="j-icon-btn" id="j-overflow-toggle" aria-label="更多"><span class="journal-overflow-btn">'+I.more+'</span></button></div></header><div class="j-overflow-panel" id="j-overflow-panel"><button data-j-overflow-action="owner">'+I.lockKeyhole+' 开发者权限</button><button data-j-overflow-action="motion">'+I.waves+' 切换动效</button></div>'}

/* ===== P0-2: D2 Hero ===== */
function buildHero(){return '<section class="j-hero"><div class="j-sun"></div><div class="j-cloud one"></div><div class="j-cloud two"></div><i class="j-leaf l1"></i><i class="j-leaf l2"></i><div class="j-hero-copy"><div class="j-hello">你好，新同学</div><h1><span class="j-lead">这份新生攻略，</span><span class="j-rest">是我希望自己大一时就能看到的。</span></h1><p class="j-hero-desc">宿舍、快递、校园网和校园路线，长颈鹿学长陪你慢慢熟悉。</p><button class="j-cta" data-j-nav="guide">开始看攻略 '+I.arrowDown+'</button></div><img class="j-mascot" src="assets/images/giraffe-senior-pink-shirt.png" alt="长颈鹿学长" fetchpriority="high" width="252" style="aspect-ratio:auto"></section>'}

function buildQuestions(){var h='<section class="j-questions"><div class="j-section-title"><h2>你可能正在找</h2><span>点开先看简答</span></div><div class="j-q-grid">';QQ.forEach(function(q){h+='<button class="j-q" data-j-quick="'+q.key+'"><span class="j-bubble">'+q.icon+'</span>'+esc(q.title)+'</button>'});return h+'</div></section>'}

function buildGuide(){var routes=getRoutes(),first=routes[0];var h='<section class="j-guide" id="j-guide"><div class="j-guide-head"><h2>新生第一周</h2><button data-j-nav="routes">全部攻略 →</button></div><div class="j-route">';if(first)h+='<div class="j-stop"><div class="j-stop-main"><img src="" alt="" style="background:var(--j-soft)" onerror="this.style.display=\'none\'"><div class="j-stop-text"><span class="j-tag">第一站 · 报到</span><h3>'+esc(first.title)+'</h3><p>'+esc((first.steps&&first.steps[0])||'从校门到寝室，一步步来。')+'</p></div></div></div>';h+='<div class="j-stop"><div class="j-mini-stops">';if(routes[1])h+='<div class="j-mini" data-j-nav="routes"><strong>'+esc(routes[1].label)+'</strong><small>'+esc(routes[1].title)+'</small></div>';h+='<div class="j-mini" data-j-nav="modules"><strong>全部板块</strong><small>按兴趣查看校园</small></div></div></div></div></section>';return h}

/* ===== P0-3: 真实高德地图 180px ===== */
function buildMap(){return '<section class="j-map-section" id="j-map-area"><div class="j-map-shell"><div class="j-map-head"><h2>校园地图</h2><span>双指缩放 · 单指滑动</span></div><div class="j-map-real" id="j-map-real"><div class="j-map-tip-bar">点击地图查看详情</div></div></div></section>'}

function initJournalMap(){var c=document.getElementById('j-map-real');if(!c||!isActive()||S.journalMap)return;var data=window.HBEU_SITE_DATA,cfg=data&&data.university&&data.university.campusMap||{},center=cfg.center||[113.920343,30.936542],zoom=(cfg.zoom||16)-2;
function tryInit(){if(!window.AMap){var wait=setTimeout(tryInit,500);if(typeof wait!=='undefined'&&!window.AMap){c.innerHTML='<div style="display:grid;place-content:center;height:100%;color:var(--j-muted);font-size:13px;text-align:center"><strong>校园地图</strong><span style="font-size:11px">点击查看完整地图</span></div>'}return}
var AMap=window.AMap;c.innerHTML='';try{var map=new AMap.Map(c,{zoom:zoom,center:center,viewMode:'2D',resizeEnable:true,layers:[new AMap.TileLayer.Satellite(),new AMap.TileLayer.RoadNet()],touchZoom:true,scrollWheel:false,dragEnable:false,zoomEnable:true});S.journalMap=map;map.on('click',function(){var t=document.querySelector('.satellite-map');if(t)t.scrollIntoView({behavior:'smooth',block:'center'})})}catch(e){c.innerHTML='<div style="display:grid;place-content:center;height:100%;color:var(--j-muted);font-size:13px;text-align:center"><strong>地图暂不可用</strong><span style="font-size:11px">请检查高德Key配置</span></div>'}}tryInit()}

/* ===== P0-1: 手账插入 main 第一位 + 手机顶栏 ===== */
window.renderMobileJournal=function(){if(!isActive()){destroyJournalMap();var o=$('.mobile-journal');if(o)o.remove();o=$('.mobile-topbar');if(o)o.remove();return}
var container=$('.mobile-journal');if(!container){container=document.createElement('div');container.className='mobile-journal';var main=document.querySelector('main');if(main)main.insertBefore(container,main.firstChild);else document.body.prepend(container)}
var tb=$('.mobile-topbar');if(!tb){var hdr=document.createElement('div');hdr.innerHTML=buildMobileTopbar();document.body.prepend(hdr.firstElementChild)}
destroyJournalMap();container.innerHTML=buildHero()+buildQuestions()+buildGuide()+buildMap();
initJournalNav();wireJournalEvents();wireOverflow();
setTimeout(initJournalMap,600)}

function initJournalNav(){var ex=$('.journal-bottom-nav');if(ex)ex.remove();var n=document.createElement('nav');n.className='journal-bottom-nav';n.setAttribute('aria-label','手机端导航');var modulesIcon='<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>';n.innerHTML='<button class="j-nav-item active" data-j-nav="home">'+I.home+'首页</button><button class="j-nav-item" data-j-nav="guide">'+I.guide+'攻略</button><button class="j-nav-ask" data-j-open-wechat>'+I.ask+'问学长</button><button class="j-nav-item" data-j-nav="map">'+I.map+'地图</button><button class="j-nav-item" data-j-nav="modules">'+modulesIcon+'板块</button>';document.body.appendChild(n)}

function journalNavTo(t){S.activeTab=t;$$('.j-nav-item').forEach(function(b){b.classList.toggle('active',b.dataset.jNav===t)})
switch(t){case'home':var h=$('.j-hero');if(h)h.scrollIntoView({behavior:'smooth',block:'start'});break;case'guide':var g=$('#j-guide');if(g)g.scrollIntoView({behavior:'smooth',block:'start'});break;case'map':var m=$('#j-map-area');if(m)m.scrollIntoView({behavior:'smooth',block:'start'});break;case'routes':var r=document.querySelector('#routeTabs,.route-strip');if(r)r.scrollIntoView({behavior:'smooth',block:'start'});break;case'modules':var mod=document.querySelector('#modules,#moduleStage');if(mod)mod.scrollIntoView({behavior:'smooth',block:'start'});break;default:var el=document.getElementById(t);if(el)el.scrollIntoView({behavior:'smooth',block:'start'})}}

function journalSyncNavState(){if(!isActive())return;var sy=window.scrollY,vh=window.innerHeight,modules=$('#modules'),map=$('#j-map-area'),guide=$('#j-guide'),nt='home';if(modules&&sy+vh*.35>=modules.offsetTop)nt='modules';else if(map&&sy+vh*.5>=map.offsetTop)nt='map';else if(guide&&sy+vh*.4>=guide.offsetTop)nt='guide';if(nt!==S.activeTab){S.activeTab=nt;$$('.j-nav-item').forEach(function(b){b.classList.toggle('active',b.dataset.jNav===nt)})}}

/* ===== P1: 微信弹层 — 昵称/微信号正确标注 ===== */
function openWechatModal(){var m=$('.journal-wechat-modal');if(!m){m=document.createElement('aside');m.className='journal-wechat-modal';m.setAttribute('aria-hidden','true');m.innerHTML='<div class="j-wechat-panel"><div class="j-wechat-avatar">鹿</div><h3>长颈鹿学长</h3><p class="j-wechat-sub">微信昵称：'+esc(W.nickname)+'</p><div class="j-wechat-id-row"><code id="j-wechat-id-code">'+esc(W.id)+'</code><button id="j-wechat-copy-btn" data-j-copy-wechat>'+I.copy+' 复制</button></div><div class="j-wechat-qr" style="background-image:url(\''+esc(W.qr)+'\')" role="img" aria-label="微信二维码"></div><p class="j-wechat-hint">'+esc(W.copy)+'</p><button class="j-wechat-close" data-j-close-wechat aria-label="关闭微信弹窗">'+I.x+'</button><p style="font-size:10px;color:var(--j-muted);margin-top:10px">长按二维码保存到相册，用微信扫一扫添加</p></div>';document.body.appendChild(m);m.addEventListener('click',function(e){if(e.target===m||e.target.closest('[data-j-close-wechat]'))closeWechatModal();else if(e.target.closest('[data-j-copy-wechat]'))copyWechatId()})}S.wechatOpen=true;m.classList.add('is-open');m.setAttribute('aria-hidden','false');journalHideNav()}
function closeWechatModal(){var m=$('.journal-wechat-modal');if(!m)return;S.wechatOpen=false;m.classList.remove('is-open');m.setAttribute('aria-hidden','true');journalShowNav()}
function copyWechatId(){var t=W.id;if(!t)return;var b=$('#j-wechat-copy-btn'),done=function(){if(!b)return;b.innerHTML=I.check+' 已复制';b.classList.add('copied');setTimeout(function(){b.innerHTML=I.copy+' 复制';b.classList.remove('copied')},2000)};if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(t).then(done).catch(function(){fallbackCopy(t,done)})}else fallbackCopy(t,done)}
function fallbackCopy(t,cb){var ta=document.createElement('textarea');ta.value=t;ta.style.cssText='position:fixed;left:-9999px';document.body.appendChild(ta);ta.select();try{document.execCommand('copy');cb()}catch(e){}document.body.removeChild(ta)}

function openQuickAnswer(k){var q=QQ.find(function(i){return i.key===k});if(!q)return;var m=$('.journal-quick-modal');if(!m){m=document.createElement('aside');m.className='journal-quick-modal';m.setAttribute('aria-hidden','true');m.innerHTML='<div class="j-quick-panel" id="j-quick-panel" role="dialog" aria-modal="true" aria-labelledby="j-quick-title"><button class="j-quick-close" type="button" data-j-close-quick aria-label="关闭回答">&times;</button><h3 id="j-quick-title"></h3><p class="j-quick-answer" id="j-quick-answer"></p><div class="j-quick-actions"><button class="j-btn-primary" id="j-quick-link"></button><button class="j-btn-ghost" data-j-close-quick>关闭</button></div></div>';document.body.appendChild(m);m.addEventListener('click',function(e){if(e.target===m||e.target.closest('[data-j-close-quick]'))closeQuickAnswer()})}S.quickOpen=k;$('#j-quick-title').textContent=q.title;$('#j-quick-answer').innerHTML=q.answer;var lb=$('#j-quick-link');lb.hidden=!q.linkTo;lb.textContent=q.linkText;lb.onclick=q.linkTo?function(){closeQuickAnswer();journalNavTo(q.linkTo)}:null;m.classList.add('is-open');m.setAttribute('aria-hidden','false');journalHideNav();setTimeout(function(){var close=$('.j-quick-close',m);if(close)close.focus()},0)}
function closeQuickAnswer(){var m=$('.journal-quick-modal');if(!m)return;S.quickOpen=null;m.classList.remove('is-open');m.setAttribute('aria-hidden','true');journalShowNav()}
function journalHideNav(){document.body.classList.add('journal-nav-hidden')}
function journalShowNav(){if(!S.wechatOpen&&!S.quickOpen)document.body.classList.remove('journal-nav-hidden')}

/* ===== P1: 溢出菜单 — 管理员入口 + 动效控制 ===== */
function wireOverflow(){var btn=$('#j-overflow-toggle'),panel=$('#j-overflow-panel');if(!btn||!panel||btn._jw)return;btn._jw=true;btn.addEventListener('click',function(e){e.stopPropagation();panel.classList.toggle('is-open')});document.addEventListener('click',function(){panel.classList.remove('is-open')});$$('[data-j-overflow-action]').forEach(function(b){b.addEventListener('click',function(){var a=b.dataset.jOverflowAction;if(a==='owner'){var ob=document.querySelector('#toggleOwner');if(ob)ob.click()}else if(a==='motion'){var mb=document.querySelector('#toggleMotion');if(mb)mb.click()}panel.classList.remove('is-open')})})}

function wireJournalEvents(){$$('[data-j-nav]').forEach(function(el){if(el._jw)return;el._jw=true;el.addEventListener('click',function(){var t=el.dataset.jNav;if(t)journalNavTo(t)})});$$('[data-j-open-wechat]').forEach(function(el){if(el._jw)return;el._jw=true;el.addEventListener('click',openWechatModal)});$$('[data-j-close-wechat]').forEach(function(el){if(el._jw)return;el._jw=true;el.addEventListener('click',closeWechatModal)});$$('[data-j-copy-wechat]').forEach(function(el){if(el._jw)return;el._jw=true;el.addEventListener('click',copyWechatId)});$$('[data-j-quick]').forEach(function(el){if(el._jw)return;el._jw=true;el.addEventListener('click',function(){openQuickAnswer(el.dataset.jQuick)})});$$('[data-j-close-quick]').forEach(function(el){if(el._jw)return;el._jw=true;el.addEventListener('click',closeQuickAnswer)})}

var st=false;window.addEventListener('scroll',function(){if(!st){requestAnimationFrame(function(){journalSyncNavState();st=false});st=true}},{passive:true});
document.addEventListener('keydown',function(e){if(e.key!=='Escape')return;if(S.quickOpen)closeQuickAnswer();else if(S.wechatOpen)closeWechatModal()});
var rt;window.addEventListener('resize',function(){clearTimeout(rt);rt=setTimeout(function(){if(isActive()&&!$('.mobile-journal')&&typeof window.renderMobileJournal==='function')window.renderMobileJournal()},200)});

var initDone=false;function maybeInit(){if(initDone||!isActive()||typeof window.renderMobileJournal!=='function')return;initDone=true;window.renderMobileJournal()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',maybeInit);else setTimeout(maybeInit,100)})();
